-- Add prompt_title field to evaluation_prompts table
-- Migration: 20250104000022_add_prompt_title

-- Add prompt_title column to evaluation_prompts
-- This stores a concise 5-word title for each base prompt
ALTER TABLE evaluation_prompts
ADD COLUMN IF NOT EXISTS prompt_title TEXT;

-- Add index for searching/filtering by title
CREATE INDEX IF NOT EXISTS idx_eval_prompts_title
ON evaluation_prompts(prompt_title);

-- Add comment documenting the field
COMMENT ON COLUMN evaluation_prompts.prompt_title IS
'Concise title (max 5 words) describing the base prompt, generated by LLM for better organization and filtering';
